# Toggle plugin state
enabled: true

# Set the header of our custom GUI
inventory-name: "Narco"

# Amount of rows to show in the /drugs GUI (1 = 9, 2 = 18, 3 = 27 etc)
inventory-rows: 1

# Sets the meta of all items
item-meta:
- "&cRight-click &fto use this drug"

# This is where you put your drugs
items:
  WHEAT:
    name: "Weed"
    data-id: 10
    price: 19.99
    color: DARK_GREEN
    message: "{PLAYER}, you have just smoked some weed!"
    effects:
      JUMP:
        duration: 10 # Amount of time (in seconds) to apply the effect for
        amplifier: 1 # Level of the effect
